name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # 修改为你自己的主分支（如：master）
    paths:
      - '**.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'compose.yml'
      

permissions:
  contents: read
  packages: write  # 推送 GHCR 所需权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest